SELECT 
'2017-11-01' AS DATE,
COUNT(CONCAT(P_UA, P_VISITOR)) AS PV,

COUNT(DISTINCT P_MUID) AS UNIQUE_VISITORS,

COUNT(CONCAT(S_UA, S_VISITOR, S_UPID, S_VIDEOID)) AS STREAM_VIEWS,

COUNT(DISTINCT S_MUID) AS UNIQUE_STREAM_VISITOR,
SUM(S_TIMESPENT) AS TOTAL_TS
	FROM /* BBCL_TABLE */
  (select t1.*, t2.*
  from
  
(select UA AS S_UA, VISITOR AS S_VISITOR, UPID AS S_UPID, VIDEOID AS S_VIDEOID, MUID AS S_MUID, 
TIMESPENT AS S_TIMESPENT
from SC_ETL_NEW.dbo.IMPORTSTREAM_SUMMARY_NEW_ADHOC
where convert(date, HKDATETIME) = '2017-10-27'
and UA in ('48', '49', '50', '51')) t1,
(
select UA as P_UA, VISITOR as P_VISITOR, MUID as P_MUID
from SC_ETL_NEW.dbo.IMPORTWEB
where HKDATE = '2017-10-27'
and UA in ('84', '85')) t2) T
