select 
COUNTRYNAME,
count(distinct VISITOR+UA+VIDEOID+UPID) as SV,
count(distinct VISITOR) as USB, 
        sum(TIMESPENT) as DURATION,
RSH_WEEK_NO,
(case
WHEN COUNTRYNAME IN ('China') THEN CONCAT(COUNTRYNAME,CITYNAME) ELSE CONTRYNAME
end) AS COUNTRYNAME
--from SC_ETL_NEW.dbo.IMPORTSTREAM_SUMMARY_NEW_7DAY,
from dbo.V_IMPORTSTREAM_NEW,
(select WEEK_NO_RSH_YYWK, FIRST_DAY_OF_WEEK_RSH, LAST_DAY_OF_WEEK_RSH
from dbo.DIM_DATE
where [DATE] = '2017-11-12' ) A
where RSH_WEEK_NO = '1746' AND RSH_TVB_PRODUCT = 'BBCL' and RSH_TVB_PRODUCT_CATEGORY = 'Live'
group by COUNTRYNAME, RSH_WEEK_NO
--GROUP BY RSH_TVB_PRODUCT, RSH_TVB_PRODUCT_CATEGORY, RSH_DEVICE_DETAIL,WEEK_NO_RSH_YYWK,
--FIRST_DAY_OF_WEEK_RSH, LAST_DAY_OF_WEEK_RSH, CITYNAME
--order by RSH_TVB_PRODUCT_CATEGORY asc, RSH_DEVICE_DETAIL desc

