--between '2017-10-30' and '2017-11-05'
select 
RSH_TVB_PRODUCT AS PRODUCT,
'TOTAL' AS CATEGORY,
RSH_DEVICE_DETAIL AS DEVICE,
'ALL' AS CITYNAME,
WEEK_NO_RSH_YYWK AS WEEKNO,
FIRST_DAY_OF_WEEK_RSH AS STARTDATE, --replace
LAST_DAY_OF_WEEK_RSH AS ENDDATE, --replace 
count(1) as PV,
        count(distinct VISITOR) as UB 
/* from SC_ETL_NEW.dbo.V_IMPORTWEB, */
from SC_ETL_NEW.dbo.IMPORTWEB_WEEK1746,
(select WEEK_NO_RSH_YYWK, FIRST_DAY_OF_WEEK_RSH, LAST_DAY_OF_WEEK_RSH
from dbo.DIM_DATE
where [DATE] = %(end_date)s ) A
where HKDATE between %(start_date)s  and %(end_date)s  --replace
and RSH_TVB_PRODUCT = 'BBCL' 
GROUP BY RSH_DEVICE_DETAIL, RSH_TVB_PRODUCT, RSH_DEVICE_DETAIL,WEEK_NO_RSH_YYWK,
FIRST_DAY_OF_WEEK_RSH, LAST_DAY_OF_WEEK_RSH
order by RSH_DEVICE_DETAIL asc