SELECT 
'2017-10-23' AS DATE,
COUNT(CONCAT(UA, VISITOR, UPID, VIDEOID)) AS STREAM_VIEWS,
COUNT(DISTINCT MUID) AS UNIQUE_STREAM_VISITOR,
SUM(TIMESPENT) AS TOTAL_TS
	FROM /* BBCL_TABLE */
  (
select *
from SC_ETL_NEW.dbo.IMPORTSTREAM_SUMMARY_NEW_1DAY
where convert(date, HKDATETIME) = '2017-10-23'
and UA in ('48', '49', '50', '51')) t