SELECT 
'2017-10-27' AS DATE,
COUNT(CONCAT(t2.P_UA, t2.P_VISITOR)) AS PV,

COUNT(DISTINCT t2.P_MUID) AS UNIQUE_VISITORS,

COUNT(CONCAT(t1.S_UA, t1.S_VISITOR, t1.S_UPID, t1.S_VIDEOID)) AS STREAM_VIEWS,

COUNT(DISTINCT t1.S_MUID) AS UNIQUE_STREAM_VISITOR,
SUM(t1.S_TIMESPENT) AS TOTAL_TS
	FROM /* BBCL_TABLE */
  (select t1.*, t2.*
  from
  
(select UA AS S_UA, VISITOR AS S_VISITOR, UPID AS S_UPID, VIDEOID AS S_VIDEOID, MUID AS S_MUID, 
TIMESPENT AS S_TIMESPENT
from SC_ETL_NEW.dbo.IMPORTSTREAM_SUMMARY_NEW_ADHOC
where convert(date, HKDATETIME) = '2017-10-27'
and UA in ('48', '49', '50', '51')) t1,
(
select UA as P_UA, VISITOR as P_VISITOR, MUID as P_MUID
from SC_ETL_NEW.dbo.IMPORTWEB
where HKDATE = '2017-10-27'
and UA in ('84', '85')) t2) T
