USE [SC_ETL_NEW]
GO


DECLARE @date DATE;

SET @date = '2017-10-25';


print @date;
print getdate();


TRUNCATE TABLE dbo.IMPORTSTREAM_SUMMARY_NEW_ADHOC;

INSERT INTO dbo.IMPORTSTREAM_SUMMARY_NEW_ADHOC
SELECT MIN(CONVERT(DATETIME, HKDATE) + CONVERT(DATETIME, HKTIME)) AS HKDATETIME,
	   MAX(TIMESPENT) - MIN(TIMESPENT) as TIMESPENT,
	   VISITOR,
	   (CASE WHEN SUM(CASE WHEN CITYNAME = 'Hong Kong' THEN 1 ELSE 0 END) > 0
			 THEN 'Hong Kong'
			 ELSE 'non-Hong Kong'
		END) AS CITYNAME,
	   MUID,
	   UA,
	   PAGEPATH,
	   VIDEOID,
	   UPID,
	   HASSTORE,
	   NULL AS ATTRIBUTES,
	   CUSTOMER_STAGE,
	   VIDEO_STAGE,
	   NULL AS QUALITY_LABEL,
	   NULL AS NETWORK_TYPE,
	   NULL AS RESOLUTION,
	   VIEW_MODE,
	   VIDEO_TYPE,
	   VIDEO_NATURE,
	   VIDEO_CONTENT_TYPE,
	   VIDEO_OWNER,
	   VIDEO_ENTRYPOINT,
	   RSH_DEVICE,
	   RSH_TVB_PRODUCT,
	   RSH_DEVICE_DETAIL,
	   NULL AS RSH_START_TIME,
	   NULL AS RSH_END_TIME,
	   NULL AS RSH_START_TIME_N1,
	   NULL AS RSH_END_TIME_N1,
	   RSH_TVB_PRODUCT_GROUP,
	   RSH_TVB_PRODUCT_SUB_GROUP,
	   RSH_TVB_PRODUCT_CATEGORY,
	   RSH_TVB_PRODUCT_SUB_CATEGORY,
	   NULL AS RSH_WEEK_NO
FROM dbo.V_IMPORTSTREAM_NEW		/* current month table */
WHERE HKDATE = @date
GROUP BY VISITOR,
		 MUID,
		 UA,
		 PAGEPATH,
		 VIDEOID,
		 UPID,
		 HASSTORE,
		 --ATTRIBUTES,
		 CUSTOMER_STAGE,
		 VIDEO_STAGE,
		 --QUALITY_LABEL,
		 --NETWORK_TYPE,
		 --RESOLUTION,
		 VIEW_MODE,
		 VIDEO_TYPE,
		 VIDEO_NATURE,
		 VIDEO_CONTENT_TYPE,
		 VIDEO_OWNER,
		 VIDEO_ENTRYPOINT,
		 RSH_DEVICE,
		 RSH_TVB_PRODUCT,
		 RSH_DEVICE_DETAIL,
		 --RSH_START_TIME,
		 --RSH_END_TIME,
		 --RSH_START_TIME_N1,
		 --RSH_END_TIME_N1,
		 RSH_TVB_PRODUCT_GROUP,
		 RSH_TVB_PRODUCT_SUB_GROUP,
		 RSH_TVB_PRODUCT_CATEGORY,
		 RSH_TVB_PRODUCT_SUB_CATEGORY
		 --RSH_WEEK_NO
		 ;

print getdate();



print getdate();

UPDATE dbo.IMPORTSTREAM_SUMMARY_NEW_ADHOC
SET RSH_START_TIME		= HKDATETIME,
	RSH_END_TIME		= dateadd(second, TIMESPENT, HKDATETIME),
	RSH_START_TIME_N1	= dateadd(second, -datepart(second, HKDATETIME), HKDATETIME),
	RSH_END_TIME_N1		= (CASE WHEN datepart(second, dateadd(second, TIMESPENT, HKDATETIME)) < 30
								THEN dateadd(second, -datepart(second, dateadd(second, dbo.MAX_IN_TWO(TIMESPENT - 30, 0), HKDATETIME)), dateadd(second, dbo.MAX_IN_TWO(TIMESPENT - 30, 0), HKDATETIME))
								ELSE dateadd(second, -datepart(second, dateadd(second, TIMESPENT, HKDATETIME)), dateadd(second, TIMESPENT, HKDATETIME))
						   END)
;

print getdate();





