select 
RSH_TVB_PRODUCT AS PRODUCT,
'TOTAL' AS CATEGORY,
RSH_DEVICE_DETAIL AS DEVICE,
'ALL' AS CITYNAME,
%(date)s as HKDATE,
count(1) as PV,
        count(distinct VISITOR) as UB 
from SC_ETL_NEW.dbo.V_IMPORTWEB 
where HKDATE = %(date)s 
and RSH_TVB_PRODUCT = 'BBCL' 
GROUP BY RSH_TVB_PRODUCT, HKDATE, RSH_DEVICE_DETAIL