/* select  
RSH_TVB_PRODUCT AS PRODUCT, 
RSH_TVB_PRODUCT_CATEGORY AS CATEGORY, 
RSH_DEVICE_DETAIL AS DEVICE, 
'ALL' AS CITYNAME, 
%(date)s AS HKDATE, 
count(distinct VISITOR+UA+VIDEOID+UPID) as SV, 
        count(distinct VISITOR) as USB, 
        sum(TIMESPENT_IN_BETWEEN) as DURATION 
from SC_ETL_NEW.dbo.IMPORTSTREAM_NEW_AGGSV
where RSH_TVB_PRODUCT = 'BBCL' and HKDATE = %(date)s
GROUP BY RSH_TVB_PRODUCT, RSH_TVB_PRODUCT_CATEGORY, RSH_DEVICE_DETAIL  */


select  
RSH_TVB_PRODUCT AS PRODUCT, 
RSH_TVB_PRODUCT_CATEGORY AS CATEGORY, 
RSH_DEVICE_DETAIL AS DEVICE, 
'ALL' AS CITYNAME, 
%(date)s AS HKDATE, 
count(distinct VISITOR+UA+VIDEOID+UPID) as SV, 
        count(distinct VISITOR) as USB, 
        sum(TIMESPENT_IN_BETWEEN) as DURATION 
from SC_ETL_NEW.dbo.IMPORTSTREAM_NEW_AGGSV
where RSH_TVB_PRODUCT = 'BBCL' and HKDATE = %(date)s
GROUP BY RSH_TVB_PRODUCT, RSH_TVB_PRODUCT_CATEGORY, RSH_DEVICE_DETAIL 
order by RSH_TVB_PRODUCT_CATEGORY asc, RSH_DEVICE_DETAIL desc