select  
RSH_TVB_PRODUCT AS PRODUCT, 
RSH_TVB_PRODUCT_CATEGORY AS CATEGORY, 
RSH_DEVICE_DETAIL AS DEVICE, 
'ALL' AS CITYNAME, 
'2017-11-13' AS HKDATE, 
count(distinct VISITOR+UA+VIDEOID+UPID) as SV, 
        count(distinct VISITOR) as USB, 
        sum(TIMESPENT) as DURATION 
from SC_ETL_NEW.dbo.V_IMPORTSTREAM_NEW 
where RSH_TVB_PRODUCT = 'BBCL' 
GROUP BY RSH_TVB_PRODUCT, RSH_TVB_PRODUCT_CATEGORY, RSH_DEVICE_DETAIL 